/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PL;


import BLL.Campus;
import BLL.Common;
import BLL.Department;
import BLL.Exceptions.UserDoesNotExistException;
import BLL.Interfaces.FormSetUp;
import BLL.User;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stephan
 */
public class DepartmentForm extends javax.swing.JFrame implements FormSetUp{

    /**
     * Creates new form DepartmentForm
     */
        private User currentUser;
    private List<Department> departmentList = new ArrayList<>();
    private int insertClick = 0;
    private int updateClick = 0;
    
    public DepartmentForm() {
        initComponents();
       
        departmentList=Department.read();
        initModel();

        currentUser = null;
       
        this.setLocationRelativeTo(null);
        if (LoginForm.enableEasterEggs) {
            Common.playMusic(2);
        } 
    }
    
      public DepartmentForm(User u) {
        initComponents();
        try {
            if (u == null) {
                currentUser = null;
                throw new UserDoesNotExistException(this);
            }
            departmentList = Department.read();
            initModel();

            currentUser = u;
            lblLoggedInUser.setText("Logged in as: " + u.getFullName() + ((u.getAccountType().equals(User.accountTypeState.ADMIN)) ? " with Admin privileges" : ""));
        } catch (UserDoesNotExistException ex) {
            ex.showMessage();
        }

        this.setLocationRelativeTo(null);
        if (LoginForm.enableEasterEggs) {
            Common.playMusic(2);
        }
    }
      
        private void initModel() {
        disableAllFields();
        setModel();
        clearAllFields();
    }

    public void setModel() {
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.setNumRows(0);
        Object columnData[] = new Object[3];
        columnData[0] = "Department ID";
        columnData[1] = "Department Name";
        columnData[2] = "Campus Name";
        model.setColumnCount(3);
        model.setColumnIdentifiers(columnData);

        for (int i = 0; i < departmentList.size(); i++) {
            Object rowData[] = new Object[3];
            rowData[0] = departmentList.get(i).getDepartmentID();
            rowData[1] = departmentList.get(i).getName();
            rowData[2] = departmentList.get(i).getCampus().getName();
            model.addRow(rowData);
        }
    }

    public void disableAllFields() {
        txtDepartmentID.setEnabled(false);
        txtDepartmentName.setEnabled(false);
        cmbCampus.setEnabled(false);
    }

    public void prepareInsert() {
        txtDepartmentID.setEnabled(false);
        txtDepartmentName.setEnabled(true);
        cmbCampus.setEnabled(true);

    }

    public void prepareUpdate() {
        txtDepartmentID.setEnabled(true);
        txtDepartmentName.setEnabled(true);
        cmbCampus.setEnabled(true);
    }

    private void clearAllFields() {
        txtDepartmentID.setText("");
        txtDepartmentID.setToolTipText(null);
        txtDepartmentName.setText("");
        txtDepartmentName.setToolTipText(null);
        cmbCampus.setSelectedIndex((cmbCampus.getItemCount() > 0) ? 0 : -1);
        cmbCampus.setToolTipText(null);
    }

    public void resetColor() {
        txtDepartmentID.setBackground(new Color(19, 54, 57));
        txtDepartmentName.setBackground(new Color(19, 54, 57));
        cmbCampus.setBackground(new Color(19, 54, 57));
    }

    public void setUIAccess(boolean value) {
      setCRUDOperations(value);
    }

    public void setCRUDOperations(boolean value) {
        btnAdd.setEnabled(value);
        btnUpdate.setEnabled(value);
        btnDelete.setEnabled(value);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtDepartmentID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtDepartmentName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        cmbCampus = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnCampus = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblLoggedInUser = new javax.swing.JLabel();
        btnLogOff = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        staffMenu2 = new javax.swing.JMenu();
        mnOpenStaff2 = new javax.swing.JMenuItem();
        stockMenu2 = new javax.swing.JMenu();
        mnOpenStockForm2 = new javax.swing.JMenuItem();
        orderStockMenu4 = new javax.swing.JMenu();
        mnOpenOrderForm2 = new javax.swing.JMenuItem();
        orderStockMenu5 = new javax.swing.JMenu();
        mnOpenCategoryForm1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        mnOpenCampusForm1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mnOpenMyProfileForm1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 115, 56));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 236, 238));
        jLabel2.setText("Stationery ...");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 162, 7));
        jLabel1.setText("Managing systems PTY ltd.");

        jPanel1.setBackground(new java.awt.Color(19, 54, 57));

        txtDepartmentID.setBackground(new java.awt.Color(19, 54, 57));
        txtDepartmentID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDepartmentID.setBorder(null);
        txtDepartmentID.setName("txtUserName"); // NOI18N
        txtDepartmentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDepartmentIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepartmentIDFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department ID:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department Name:");

        txtDepartmentName.setBackground(new java.awt.Color(19, 54, 57));
        txtDepartmentName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDepartmentName.setBorder(null);
        txtDepartmentName.setName("txtUserName"); // NOI18N
        txtDepartmentName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDepartmentNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepartmentNameFocusLost(evt);
            }
        });

        cmbCampus.setBackground(new java.awt.Color(19, 54, 57));
        cmbCampus.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbCampus.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Campus: ");

        btnCampus.setBackground(new java.awt.Color(0, 115, 56));
        btnCampus.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCampus.setForeground(new java.awt.Color(255, 255, 255));
        btnCampus.setText("Campuses");
        btnCampus.setActionCommand("Log Off");
        btnCampus.setName("btnInsertRecord"); // NOI18N
        btnCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCampusActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Department Form:");

        lblLoggedInUser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblLoggedInUser.setForeground(new java.awt.Color(255, 255, 255));
        lblLoggedInUser.setText("Logged In User");

        btnLogOff.setBackground(new java.awt.Color(0, 115, 56));
        btnLogOff.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLogOff.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOff.setText("Log Off");
        btnLogOff.setName("btnInsertRecord"); // NOI18N
        btnLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOffActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 115, 56));
        btnAdd.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Insert Record");
        btnAdd.setName("btnInsertRecord"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 115, 56));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Record");
        btnUpdate.setName("btnUpdateRecord"); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 115, 56));
        btnDelete.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Record");
        btnDelete.setToolTipText("");
        btnDelete.setName("btnDeleteRecord"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblData.setBackground(new java.awt.Color(204, 204, 204));
        tblData.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), null, null)));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoggedInUser)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 69, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(25, 25, 25)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtDepartmentName)
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtDepartmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addGap(88, 88, 88)
                                                    .addComponent(cmbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btnCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnLogOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoggedInUser)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDepartmentID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDepartmentName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(cmbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        staffMenu2.setText("Staff");
        staffMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        staffMenu2.setFont(Common.setFont(0,0)
        );
        staffMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffMenu2.setIconTextGap(20);

        mnOpenStaff2.setFont(Common.setFont(0, 1)
        );
        mnOpenStaff2.setText("Open Staff Form");
        mnOpenStaff2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpenStaff2ActionPerformed(evt);
            }
        });
        staffMenu2.add(mnOpenStaff2);

        jMenuBar1.add(staffMenu2);

        stockMenu2.setText("Stock");
        stockMenu2.setFont(Common.setFont(0,0));
        stockMenu2.setIconTextGap(10);

        mnOpenStockForm2.setFont(Common.setFont(0,1));
        mnOpenStockForm2.setText("Open Stock Form");
        mnOpenStockForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpenStockForm2ActionPerformed(evt);
            }
        });
        stockMenu2.add(mnOpenStockForm2);

        jMenuBar1.add(stockMenu2);

        orderStockMenu4.setText("Order Stock");
        orderStockMenu4.setFont(Common.setFont(0,0));
        orderStockMenu4.setIconTextGap(10);

        mnOpenOrderForm2.setFont(Common.setFont(0,1));
        mnOpenOrderForm2.setText("Open Order Form");
        mnOpenOrderForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpenOrderForm2ActionPerformed(evt);
            }
        });
        orderStockMenu4.add(mnOpenOrderForm2);

        jMenuBar1.add(orderStockMenu4);

        orderStockMenu5.setText("Category");
        orderStockMenu5.setFont(Common.setFont(0,0));
        orderStockMenu5.setIconTextGap(10);

        mnOpenCategoryForm1.setFont(Common.setFont(0,1));
        mnOpenCategoryForm1.setText("Open Category Form");
        mnOpenCategoryForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpenCategoryForm1ActionPerformed(evt);
            }
        });
        orderStockMenu5.add(mnOpenCategoryForm1);

        jMenuBar1.add(orderStockMenu5);

        jMenu6.setText("Department");
        jMenu6.setFont(Common.setFont(0,0));
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Campus");
        jMenu7.setFont(Common.setFont(0,0));

        mnOpenCampusForm1.setFont(Common.setFont(0,1));
        mnOpenCampusForm1.setText("Open Campus Form");
        mnOpenCampusForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpenCampusForm1ActionPerformed(evt);
            }
        });
        jMenu7.add(mnOpenCampusForm1);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("My Profile");
        jMenu8.setFont(Common.setFont(0,0));

        mnOpenMyProfileForm1.setFont(Common.setFont(0,1));
        mnOpenMyProfileForm1.setText("Open My Profile Form");
        mnOpenMyProfileForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpenMyProfileForm1ActionPerformed(evt);
            }
        });
        jMenu8.add(mnOpenMyProfileForm1);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDepartmentIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepartmentIDFocusGained
        
        Common.focusGain("ID number", txtDepartmentID);
    }//GEN-LAST:event_txtDepartmentIDFocusGained

    private void txtDepartmentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepartmentIDFocusLost

        Common.focusLost("ID number", txtDepartmentID);
    }//GEN-LAST:event_txtDepartmentIDFocusLost

    private void txtDepartmentNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepartmentNameFocusGained
        Common.focusGain("Department Name", txtDepartmentName);
    }//GEN-LAST:event_txtDepartmentNameFocusGained

    private void txtDepartmentNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepartmentNameFocusLost
        Common.focusLost("Department Name", txtDepartmentName);
    }//GEN-LAST:event_txtDepartmentNameFocusLost

    private void btnCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCampusActionPerformed
        
    }//GEN-LAST:event_btnCampusActionPerformed

    private void btnLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOffActionPerformed
        
        if (currentUser != null) {
            Common.logOff(this);
        } else {
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogOffActionPerformed

    private void mnOpenStaff2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpenStaff2ActionPerformed

        StaffForm staff = new StaffForm(currentUser);
        staff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnOpenStaff2ActionPerformed

    private void mnOpenStockForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpenStockForm2ActionPerformed

        new StockForm(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnOpenStockForm2ActionPerformed

    private void mnOpenOrderForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpenOrderForm2ActionPerformed

        OrderForm orderForm = new OrderForm(currentUser);
        orderForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnOpenOrderForm2ActionPerformed

    private void mnOpenCategoryForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpenCategoryForm1ActionPerformed

        new CategoryForm(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnOpenCategoryForm1ActionPerformed

    private void mnOpenCampusForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpenCampusForm1ActionPerformed

        new CampusForm(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnOpenCampusForm1ActionPerformed

    private void mnOpenMyProfileForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpenMyProfileForm1ActionPerformed

        new MyProfileForm(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnOpenMyProfileForm1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (insertClick == 0) {
            insertClick++;
            setUIAccess(false);
            btnAdd.setEnabled(true);
            clearAllFields();
            prepareInsert();
        } else {
            resetColor();

            String departmentName = null;
            String campusName = null;

            departmentName = txtDepartmentName.getText();
            campusName =  (cmbCampus.getItemCount() > 0) ? cmbCampus.getSelectedItem().toString() : "";

            boolean check = true;

            if (Common.checkInput(departmentName) != 1 || departmentName.length() > 50) {
                check = false;
                txtDepartmentName.setBackground(Color.red);
                txtDepartmentName.setToolTipText("Only alphabetical characters. Max 50 characters");
            }
            if (Common.checkInput(campusName) != 1 || departmentName.length() > 50) {
                check = false;
                cmbCampus.setBackground(Color.red);
                cmbCampus.setToolTipText("Only alphabetical characters. Max 50 characters");
            }

            if (check) {
                int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this data?", "Confirmation.", JOptionPane.YES_NO_OPTION);
                if (option == 0) {
                    Department.create(new Department(0, departmentName,Campus.read(campusName)));
                    departmentList = Department.read();
                    setModel();
                }
                clearAllFields();
                disableAllFields();
                resetColor();
                insertClick = 0;
                setUIAccess(true);
            } else {
                int option = JOptionPane.showConfirmDialog(this, "There were some errors, would you like to fix them?", "Confirmation.", JOptionPane.YES_NO_OPTION);
                if (option == 1) {
                    clearAllFields();
                    disableAllFields();
                    resetColor();
                    insertClick = 0;
                    setUIAccess(true);
                }
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (updateClick == 0) {
            updateClick++;
            setUIAccess(false);
            btnUpdate.setEnabled(true);
            prepareUpdate();
        } else {
            resetColor();

            String departmetID =null;
            String departmentName = null;
            String campusName = null;
            
            departmetID=txtDepartmentID.getText();
            departmentName = txtDepartmentName.getText();
            campusName =  (cmbCampus.getItemCount() > 0) ? cmbCampus.getSelectedItem().toString() : "";


            boolean check = true;

            if (Common.checkInput(departmetID) != 2) {
                check = false;
                txtDepartmentID.setBackground(Color.red);
                txtDepartmentID.setToolTipText("Only numerical characters");
            }
           if (Common.checkInput(departmentName) != 1 || departmentName.length() > 50) {
                check = false;
                txtDepartmentName.setBackground(Color.red);
                txtDepartmentName.setToolTipText("Only alphabetical characters. Max 50 characters");
            }
            if (Common.checkInput(campusName) != 1 || departmentName.length() > 50) {
                check = false;
                cmbCampus.setBackground(Color.red);
                cmbCampus.setToolTipText("Only alphabetical characters. Max 50 characters");
            }


            if (check) {
                int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to update this data?", "Confirmation.", JOptionPane.YES_NO_OPTION);
                if (option == 0) {
                    Department.update(new Department(Integer.valueOf(departmetID), departmentName,Campus.read(campusName)));
                    departmentList = Department.read();
                    setModel();
                }
                clearAllFields();
                disableAllFields();
                resetColor();
                updateClick = 0;
                setUIAccess(true);
            } else {
                int option = JOptionPane.showConfirmDialog(this, "There were some errors, would you like to fix them?", "Confirmation.", JOptionPane.YES_NO_OPTION);
                if (option == 1) {
                    clearAllFields();
                    disableAllFields();
                    resetColor();
                    updateClick = 0;
                    setUIAccess(true);
                }
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Delete Record
        if (Common.checkInput(txtDepartmentID.getText()) == 2 && Department.read(Integer.parseInt(txtDepartmentID.getText())) != null) {
            int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this data?", "Confirmation.", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                Department.delete( Integer.valueOf(txtDepartmentID.getText()));
                clearAllFields();
                departmentList = Department.read();
                setModel();
            }
        } else {
            JOptionPane.showMessageDialog(null, "No valid stock item selected");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int i = tblData.getSelectedRow();

        Department selectedDepartment;
        selectedDepartment = new Department(Integer.valueOf(tblData.getValueAt(i, 0).toString()),
            tblData.getValueAt(i, 1).toString(),
            (Campus.read(tblData.getValueAt(i, 2).toString())));
        txtDepartmentID.setText(String.valueOf(selectedDepartment.getDepartmentID()));
        txtDepartmentName.setText(selectedDepartment.getName());
        cmbCampus.setSelectedItem(selectedDepartment.getCampus().getName() + " - " + selectedDepartment.getCampus().getName());
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCampus;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogOff;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCampus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblLoggedInUser;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem mnOpenCampusForm1;
    private javax.swing.JMenuItem mnOpenCategoryForm1;
    private javax.swing.JMenuItem mnOpenMyProfileForm1;
    private javax.swing.JMenuItem mnOpenOrderForm2;
    private javax.swing.JMenuItem mnOpenStaff2;
    private javax.swing.JMenuItem mnOpenStockForm2;
    private javax.swing.JMenu orderStockMenu4;
    private javax.swing.JMenu orderStockMenu5;
    private javax.swing.JMenu staffMenu2;
    private javax.swing.JMenu stockMenu2;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtDepartmentID;
    private javax.swing.JTextField txtDepartmentName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setNavigation(boolean flag) {
        
    }
}
